---
- name: add GPG key into apt
  apt_key:
    url=https://repos.influxdata.com/influxdb.key
    state=present
  tags:
  - influx

- name: add influx repository
  apt_repository:
    repo='deb https://repos.influxdata.com/debian jessie stable'
    state=present
  register: influxdb_repo_added
  tags:
  - influx

- name: apt update cache
  apt:
    update_cache: yes
  when: influxdb_repo_added.changed
  tags:
  - influx

- name: install influxDb
  apt:
    pkg=influxdb
    state=present
  tags:
  - influx

- name: create directory for neo4j pid. sometimes it fails
  file:
    path=/var/lib/neo4j
    state=directory
    mode=0755
  tags:
  - influx

- name: enable influxdb
  service:
    name=influxdb
    state=started
    enabled=yes
  tags:
  - influx

